### ISSUE TITLE
Class WrappingServerIntegrationTest not found

### ISSUE THREAD

**Issue by cfedk** [neo4j-examples/sdn4-cineasts#1]
Have played around with versioning in POM, no joy.

**Comment by luanne** [comment]
Please use the 4.0-RC1 branch https://github.com/neo4j-examples/sdn4-cineasts/tree/4.0-RC1
There have been many updates since Milestone 1. Merging this branch into master is on the to-do list.

**Comment by luanne** [comment]
master updated to 4.0.0.RELEASE
